name = "bd01"
main = "worker/index.ts"
compatibility_date = "2024-10-14"

# Assets configuration - serves files from dist/
assets = { directory = "./dist", binding = "ASSETS" }

# Build configuration
[build]
command = "npm run build"
watch_dirs = ["client/src", "worker"]
