name = "bd01"
main = "worker/index.ts"
compatibility_date = "2024-10-14"

# Workers Sites configuration
[site]
bucket = "./dist"

# Build configuration
[build]
command = "npm run build"
watch_dirs = ["client/src", "worker"]
